TERMUX_PKG_HOMEPAGE=https://github.com/aous72/OpenJPH
TERMUX_PKG_DESCRIPTION="Open-source implementation of JPEG2000 Part-15 (HTJ2K)"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.21.2"
TERMUX_PKG_SRCURL=https://github.com/aous72/OpenJPH/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=SKIP_CHECKSUM
TERMUX_PKG_DEPENDS="libc++, libtiff"
TERMUX_PKG_BUILD_IN_SRC=false
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_BUILD_TYPE=Release
-DOJPH_DISABLE_INTEL_SIMD=ON
-DOJPH_BUILD_TESTS=OFF
-DOJPH_BUILD_EXECUTABLES=OFF
-DBUILD_SHARED_LIBS=ON
"
